### ISSUE TITLE
Route colors should be more distinct 

### ISSUE THREAD

**Issue by vchernetsky** [amigocloud/modified-tripplanner#85]
![screen shot 2016-05-13 at 10 20 18 am](https://cloud.githubusercontent.com/assets/1840126/15256044/5e833a8a-18f4-11e6-8ff5-6be6aa3bea5f.png)

**Comment by rburhum** [comment]
Let's not pick random colors. Let's use one of the qualitative color schemes from Color Brewer 2.0 http://colorbrewer2.org/ The third one seems nice.
![screen shot 2016-05-13 at 10 26 44 am](https://cloud.githubusercontent.com/assets/138918/15256202/35bbb676-18f5-11e6-9abe-ca00a985fd1d.png)

**Comment by lukewhyte** [comment]
@rburhum: That works for me. However, originally I did choose from the divergent color schemes on Color Brewer, but then switched to sequential b/c I wanted to create a somewhat obvious distinction between different modes (walk, bus) and different legs of the same mode (2 sequential bus routes). Ultimately, in order to do this, I ended up picking one sequential scheme for both busses and lightrail – iterating over the scheme for each leg of the same mode – and then picking distinct random colors from the sequential schemes for walking, car and bike.

Do you have ideas for how to better solve the issue described above using the divergent color schemes?

**Comment by rburhum** [comment]
That is great to hear. Apologies I had just assumed we picked random colors.

Mmm, one possible option is to mix these two approaches. Pick a set of colors from the quantitative color schemes, no need to do random, pick your favorite ones for showing the initial route differences. If there are 5 different route options, you will have 5 very distinct colors using this approach

On the mouse over for a particular option (or perhaps when selecting details?) switch to a color scheme for each mode change with colors for each mode switch. Instead of worrying that two legs that have the same mode but are different routes (e.g. switching from one bus route to another bus route), we can maintain the same colors, but drop a generic icon for those cases that indicates a change something like this 
![terminal_transfer_bus_icon](https://cloud.githubusercontent.com/assets/138918/15256730/ba32e3b4-18f7-11e6-81e8-6feacdf79819.png).

What do you think @marsxul ?

**Comment by marsxul** [comment]
Hey guys,

Let's do this, Bus routes in black, light rail in blue, caltrain in orange, bart as it is according to its own. ACE and capital corridor purple.  Let's keep it simple, no need to change colors for trips using multiple routes.  Focus on the color difference by mode type.  dotted light blue for walking and dotted red for cycling are great.  

let me know if you have any questions.

**Comment by marsxul** [comment]
I am actually enjoying the aesthetic of it now.  Let's keep bus blue and Light rail green.  Caltrain orange, bart has its own colors.  Keep the colors the same for the whole trip.  The faded or transparent look on connecting trips is not a good look for customers seeking information.

**Comment by lukewhyte** [comment]
@marsxul – just want to make sure I have this correct:
- Bus: blue
- Light rail: green
- Caltrain: orange
- Cycling: red (dashed)
- Walking: blue (dashed) or should we go yellow b/c busses are now blue?

**Comment by marsxul** [comment]
@lukewhyte  - looks good to me, Let's keep walking blue - dashed, perhaps a slightly lighter shade of blue.  Yellows are hard to see especially when dashed.
